#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Mentor Graphics Questa Advanced Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Aug 19 18:05:41 CST 2023
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
bin_path="/home/mentor/questasim/linux_x86_64"
set -Eeuo pipefail
source uart_top_tb_elaborate.do 2>&1 | tee -a elaborate.log

