######################################################################
#
# File name : uart_top_tb_elaborate.do
# Created on: Sat Aug 19 18:05:41 CST 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vopt -64 +acc=npr -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -work xil_defaultlib xil_defaultlib.uart_top_tb xil_defaultlib.glbl -o uart_top_tb_opt
