######################################################################
#
# File name : uart_top_tb_compile.do
# Created on: Sat Aug 19 18:05:40 CST 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xil_defaultlib

vmap xil_defaultlib questa_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../k325t.srcs/sources_1/ip/clk_wiz_0" \
"../../../../k325t.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
"../../../../k325t.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.v" \
"../../../../../../src/rtl/uart_rx.v" \
"../../../../../../src/rtl/uart_top.v" \
"../../../../../../src/rtl/uart_tx.v" \
"../../../../../../src/tb/uart_top_tb.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

