######################################################################
#
# File name : uart_top_tb_simulate.do
# Created on: Sat Aug 19 18:05:42 CST 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib uart_top_tb_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {uart_top_tb_wave.do}

view wave
view structure
view signals

do {uart_top_tb.udo}

run 1000ns
