######################################################################
#
# File name : uart_top_tb_wave.do
# Created on: Sat Aug 19 17:56:03 CST 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
